# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: dev 
#      MONGO_INITDB_ROOT_PASSWORD: dev 

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
#      ME_CONFIG_MONGODB_ADMINPASSWORD: dev


  mongo-init:
    build: ./mongo-init
    links:
      - mongo
